export enum Actions {
  LOAD_GRAPH = 'LOAD_GRAPH',
  SET_THEME = 'SET_THEME',
  TOGGLE_NODE = 'TOGGLE_NODE',
  LOAD_STATE = 'LOAD_STATE',
  FETCH_GRAPH = 'FETCH_GRAPH',
  FETCH_GRAPH_SUCCESS = 'FETCH_GRAPH_SUCCESS',
  FETCH_GRAPH_FAILED = 'FETCH_GRAPH_FAILED',
}
